"""
knowledge_base/diseases.py — Verified crop disease knowledge for KisanAI RAG

Each entry contains disease-specific, India-relevant treatment information
that will be embedded into ChromaDB and retrieved to ground Gemini responses.
"""

DISEASES = [
    {
        "id": "tomato_early_blight",
        "disease": "Early Blight",
        "crop": "Tomato",
        "tamil_name": "ஆரம்ப கருகல் நோய்",
        "symptoms": "Brown spots with yellow rings on lower leaves. Spots have a target-board pattern.",
        "cause": "Fungus called Alternaria solani. Spreads in warm, humid weather.",
        "treatment": "Spray Mancozeb 75% WP at 2.5g per litre of water. Apply every 7 days for 3 weeks. Also use Copper Oxychloride 50% WP at 3g per litre as alternative.",
        "organic_treatment": "Spray Neem oil 5ml per litre of water. Apply Trichoderma viride 5g per litre.",
        "prevention": "Remove infected leaves immediately. Avoid watering from above. Keep 60cm space between plants. Rotate crops every season.",
        "best_time_to_spray": "Early morning before 9am or after 5pm. Never spray in hot afternoon sun.",
        "available_in_india": "Mancozeb (Dithane M-45), Copper Oxychloride (Blitox), Trichoderma (Ecosom-TH)",
        "cost": "Mancozeb 100g costs approximately Rs 50-80 at local agri shops",
    },
    {
        "id": "tomato_late_blight",
        "disease": "Late Blight",
        "crop": "Tomato",
        "tamil_name": "கடும் கருகல் நோய்",
        "symptoms": "Dark brown or black patches on leaves and stems. White fungal growth on underside of leaves. Fruits rot quickly.",
        "cause": "Oomycete called Phytophthora infestans. Very dangerous — can destroy entire crop in 3-5 days in rainy season.",
        "treatment": "Spray Metalaxyl + Mancozeb (Ridomil Gold) at 2.5g per litre immediately. Also Cymoxanil + Mancozeb (Curzate) at 3g per litre. Act fast — do not delay.",
        "organic_treatment": "Spray Bordeaux mixture (1%) on all plant parts. Apply Pseudomonas fluorescens 10g per litre.",
        "prevention": "Plant resistant varieties like Arka Rakshak. Ensure good drainage. Avoid overhead irrigation. Destroy infected plants completely — do not compost.",
        "best_time_to_spray": "Spray immediately when detected. Every 5 days during rainy season.",
        "available_in_india": "Ridomil Gold MZ, Curzate M8, Bordeaux mixture",
        "cost": "Ridomil Gold 100g costs approximately Rs 150-200",
    },
    {
        "id": "cercospora_leaf_spot",
        "disease": "Cercospora Leaf Spot",
        "crop": "General — affects tomato, chilli, brinjal, groundnut",
        "tamil_name": "செர்கோஸ்போரா இலை புள்ளி நோய்",
        "symptoms": "Small circular spots with grey or white centre and brown border on leaves. Spots enlarge and merge. Leaves turn yellow and fall.",
        "cause": "Fungus Cercospora species. Spreads through rain splash and wind. Common in Tamil Nadu monsoon season.",
        "treatment": "Spray Carbendazim 50% WP at 1g per litre of water. Alternatively Propiconazole 25% EC at 1ml per litre. Repeat after 10 days.",
        "organic_treatment": "Spray Neem oil 3ml plus garlic extract 10ml per litre of water. Apply wood ash on soil around plant base.",
        "prevention": "Use certified disease-free seeds. Remove and burn fallen leaves. Avoid working in field when plants are wet.",
        "best_time_to_spray": "Early morning. Spray on both upper and lower surfaces of leaves.",
        "available_in_india": "Bavistin (Carbendazim), Tilt (Propiconazole), Neem oil (many brands)",
        "cost": "Carbendazim 100g costs approximately Rs 40-60",
    },
    {
        "id": "powdery_mildew",
        "disease": "Powdery Mildew",
        "crop": "General — affects cucumbers, pumpkin, grapes, chilli",
        "tamil_name": "பொடி பூஞ்சை நோய்",
        "symptoms": "White powdery coating on upper surface of leaves. Leaves curl and turn yellow. Affects young leaves first.",
        "cause": "Fungus Erysiphe species. Spreads in dry weather with high humidity at night. Common in October-December in Tamil Nadu.",
        "treatment": "Spray Wettable Sulphur 80% at 3g per litre of water. Or Hexaconazole 5% EC at 2ml per litre. Repeat every 10-14 days.",
        "organic_treatment": "Spray baking soda solution (5g per litre). Neem oil 5ml per litre. Diluted milk spray (1 part milk, 9 parts water).",
        "prevention": "Plant resistant varieties. Ensure good air circulation between plants. Avoid excess nitrogen fertilizer.",
        "best_time_to_spray": "Early morning. Do not spray sulphur when temperature exceeds 35 degrees Celsius.",
        "available_in_india": "Sulfex (Wettable Sulphur), Hexadhan (Hexaconazole), Contaf (Hexaconazole)",
        "cost": "Wettable Sulphur 500g costs approximately Rs 60-80",
    },
    {
        "id": "leaf_rust",
        "disease": "Rust",
        "crop": "General — affects wheat, sorghum, groundnut, beans",
        "tamil_name": "துரு நோய்",
        "symptoms": "Orange or brown powdery pustules on undersides of leaves. Upper surface shows yellow spots above pustules. Severely infected leaves dry up.",
        "cause": "Fungus Puccinia species or Uromyces species. Wind-borne spores spread rapidly.",
        "treatment": "Spray Propiconazole 25% EC at 1ml per litre of water. Or Mancozeb 75% WP at 2.5g per litre. Treat early for best results.",
        "organic_treatment": "Spray Neem oil 5ml per litre. Remove and destroy heavily infected plant parts.",
        "prevention": "Use rust-resistant varieties. Balanced fertilization — excess nitrogen increases rust susceptibility. Crop rotation every 2 seasons.",
        "best_time_to_spray": "Early morning. Repeat every 10 days until disease is controlled.",
        "available_in_india": "Tilt 250EC (Propiconazole), Dithane M-45 (Mancozeb)",
        "cost": "Propiconazole 100ml costs approximately Rs 120-150",
    },
    {
        "id": "mosaic_virus",
        "disease": "Mosaic Virus",
        "crop": "General — affects tomato, chilli, cucumber, beans",
        "tamil_name": "மொசைக் வைரஸ் நோய்",
        "symptoms": "Yellow-green mottled pattern on leaves. Leaves curl inward. Stunted plant growth. Fruits are small and deformed.",
        "cause": "Transmitted by aphids and whiteflies. No chemical cure once infected.",
        "treatment": "No direct cure for virus. Remove and destroy infected plants immediately to stop spread. Control the insect vectors with Imidacloprid 17.8% SL at 0.5ml per litre to kill aphids and whiteflies.",
        "organic_treatment": "Yellow sticky traps to catch whiteflies. Neem oil spray 5ml per litre to repel insects. Reflective mulch to confuse aphids.",
        "prevention": "Use virus-free certified seeds. Control weeds around field. Plant marigold as border crop to repel insects. Spray mineral oil to prevent aphid feeding.",
        "best_time_to_spray": "Spray insecticides in evening to avoid killing bees.",
        "available_in_india": "Confidor (Imidacloprid), Yellow sticky traps from any agri shop",
        "cost": "Yellow sticky traps Rs 5-10 each. Confidor 100ml Rs 200-250",
    },
    {
        "id": "healthy_crop",
        "disease": "Healthy",
        "crop": "General",
        "tamil_name": "ஆரோக்கியமான பயிர்",
        "symptoms": "No disease symptoms. Green healthy leaves.",
        "cause": "Not applicable",
        "treatment": "No treatment needed. Continue good farming practices.",
        "organic_treatment": "Apply compost or vermicompost to maintain soil health. Spray cow urine solution (diluted 1:10) as preventive.",
        "prevention": "Regular monitoring every week. Balanced NPK fertilization. Proper irrigation. Crop rotation.",
        "best_time_to_spray": "Preventive neem oil spray once every 15 days.",
        "available_in_india": "Vermicompost, Neem cake, Panchagavya from local agri shop",
        "cost": "Vermicompost 5kg Rs 100-150",
    },
]
